# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-20 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20171220_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='nag_after',
        ),
        migrations.RemoveField(
            model_name='check',
            name='nag_interval',
        ),
        migrations.RemoveField(
            model_name='check',
            name='nag_status',
        ),
    ]
