# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-20 13:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20171220_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='interval',
            field=models.DurationField(default=datetime.timedelta(0, 3600)),
        ),
    ]
