# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-20 15:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_check_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='nag_after',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='check',
            name='nag_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='interval',
            field=models.DurationField(default=datetime.timedelta(0, 7200)),
        ),
    ]
