# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-20 15:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20171220_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='interval',
            field=models.DurationField(default=datetime.timedelta(0, 3600)),
        ),
    ]
